name: Build "turnip"

on:
  workflow_dispatch:
  schedule:
  - cron: "20 5 1,15 * *"

jobs:
  start_building_turnip:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3

    - name: Prepare environment
      run: |
        sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
        sudo apt update
        sudo apt build-dep mesa -y
        sudo apt install libedit-dev
        sudo apt install libzstd-dev libelf-dev libncurses-dev
    - name: Execute build script
      run: bash ./turnip_builder.sh

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Upload meson and ninja logs for debugging-${{ matrix.runs-on }}
        path: |
          turnip_workdir/ninja_log
          turnip_workdir/mesa-main/build-android-aarch64/meson-logs/meson-log.txt

    - name: Release "turnip build - Mesa-25.1.0-devel"
      uses: softprops/action-gh-release@v1
      with:
        body: Turnip magisk module
        tag_name: workflow_${{github.run_number}}
        name: Release ${{github.run_number}}
        files: |
           turnip_workdir/turnip.zip
           turnip_workdir/turnip_adrenotools.zip
